# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/get_random_word/142264444
Accept: application/json

###

GET https://api.dictionaryapi.dev/api/v2/entries/en/natural
Accept: application/json